# Generated by Django 4.0 on 2022-09-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='old_price',
            new_name='new_price',
        ),
    ]
